# Generated by Django 3.0.1 on 2020-04-26 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='venues/default.jpg', upload_to='venues')),
                ('address',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue',
                                   to='geolocation.Address')),
                ('admin',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venues',
                                   to=settings.AUTH_USER_MODEL)),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  to='geolocation.Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('max_attendees', models.IntegerField(verbose_name='Max attendees')),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_slots',
                                            to='venues.Venue')),
            ],
        ),
    ]
