# Generated by Django 3.0.1 on 2020-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('Resturaunt', 'Resturaunt'), ('Grocery', 'Grocery'), ('Bar', 'Bars'), ('Coffee', 'Coffee'), ('Gym', 'Gym'), ('Gas', 'Gas'), ('Mail', 'Mail'), ('Laundry', 'Laundry'), ('Repair', 'Repair'), ('Beauty', 'Beauty'), ('Library', 'Library')], default='Grocery', max_length=20),
            preserve_default=False,
        ),
    ]
