# Generated by Django 3.0.1 on 2020-04-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('Resturaunt', 'Resturaunt'), ('Grocery', 'Grocery'), ('Coffee', 'Coffee'), ('Gym', 'Gym'), ('Gas', 'Gas'), ('Mail', 'Mail'), ('Laundry', 'Laundry'), ('Repair', 'Repair'), ('Beauty', 'Beauty'), ('Education', 'Education')], max_length=20),
        ),
    ]
