# Generated by Django 3.0.1 on 2020-04-27 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0003_auto_20200427_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
