# Generated by Django 3.0.1 on 2020-04-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_auto_20200427_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
