# Generated by Django 3.0.1 on 2020-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_auto_20200428_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
