# Generated by Django 3.0.1 on 2020-04-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('venues', '0007_auto_20200428_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
