# Generated by Django 3.0.1 on 2020-04-30 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0008_venue_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='attendees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
