# Generated by Django 3.0.1 on 2020-04-30 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venues', '0009_auto_20200430_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='time_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
