# Generated by Django 2.2.9 on 2020-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_auto_20200602_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='attendee_count',
            field=models.IntegerField(default=0),
        ),
    ]
