# Generated by Django 2.2.9 on 2020-06-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_auto_20200614_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_hour', models.IntegerField()),
                ('start_minute', models.IntegerField()),
                ('stop_hour', models.IntegerField()),
                ('stop_minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_length', models.IntegerField()),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venues.Venue')),
                ('weekdays', models.ManyToManyField(to='venues.ScheduleDay')),
            ],
        ),
    ]
