# Generated by Django 2.2.9 on 2020-06-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_venue_visit_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
