# Generated by Django 2.2.9 on 2020-07-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_auto_20200712_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='lead_time_hours',
            field=models.FloatField(default=0),
        ),
    ]
