# Generated by Django 2.2.9 on 2020-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_venue_lead_time_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(choices=[('All', 'All'), ('Eldery', 'Elderly'), ('Frontline', 'Frontline')], default='All', max_length=25),
        ),
    ]
