# Generated by Django 2.2.9 on 2020-07-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='form_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='requires_form',
            field=models.BooleanField(default=False),
        ),
    ]
