# Generated by Django 2.2.9 on 2020-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_auto_20200715_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='share_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
