# Generated by Django 2.2.9 on 2020-07-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_venue_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='allows_named_attendees',
            field=models.BooleanField(default=False),
        ),
    ]
