# Generated by Django 2.2.9 on 2020-08-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0024_venue_allows_named_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
