# Generated by Django 3.0.1 on 2020-05-10 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20200427_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peertovenuehandshake',
            old_name='person',
            new_name='user',
        ),
    ]
