# Generated by Django 2.2.9 on 2020-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_account_is_venueadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='users/theresoapp.jpg', upload_to='users'),
        ),
        migrations.AddField(
            model_name='account',
            name='share_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
