# Generated by Django 2.2.9 on 2020-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='default_cost',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=100),
            preserve_default=False,
        ),
    ]
