# Generated by Django 2.2.9 on 2020-05-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce', '0002_subscriptiontype_default_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='daily_allowed_scans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='default_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(
                choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large'), ('E', 'Enterprise')],
                max_length=5),
        ),
    ]
